spring.application.name=travel-agency
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/travel_agency?createDatabaseIfNotExist=true
spring.jpa.hibernate.ddl-auto=update
server.error.include-message=always
sda.fieldA = "field A"
sda.fieldB = "field B"
